### PR TITLE
Center auth component on login page

### PR DESCRIPTION
**Pull request by Yohanan-Negash**
Fixes : #22 

## Solution
I added some CSS properties that center the `Auth` component on the login page. 

## Testing
1. Start the supabase CLI, `supabase start` 
2. `yarn dev`, to start the dev server
3.  Navigate to `localhost:3000/signin` (signin page)  and observe the change made on the auth component

###### Before adding styles
Screen Shot 2022-01-01 at 1 11 05 AM

###### After adding styles
Screen Shot 2022-01-01 at 1 09 49 AM

### CODE REVIEW

**Comment by iAmWillShepherd** [comment]
This PR doesn't address the change indicated in the title, but makes changes to the homepage instead. This PR conflicts with PR#43 and we have a couple of options we can take to resolve the issue:

1. Merge the base branch of PR #43 into this branch
2. Close this PR and merge changes into the base branch of PR #43 

I don't there's a way of avoiding merge conflicts, so I think option one would be best. Also, the testing steps don't work for anyone trying to run this. Refer to PR #43 for one good testing steps look like.

**Review by iAmWillShepherd — CHANGES_REQUESTED** [review]
This PR actually has nothing to do with the account page and conflicts with the work being done in #43. The two PRs will need to be merged, consult the comment I left on the PR for the next steps.

**Comment by iAmWillShepherd** [comment]
I changed the base branch of this PR (the conflicts need to be taken care of). Please update your PR title and description to highlight that these updates are for the login page, not the account page.

**Comment by Yohanan-Negash** [comment]
Since this PR conflicts with PR #43 I merged the base branch of PR #43 into this one as you suggested.

**Review by iAmWillShepherd — COMMENTED** [review]
Looks good 🔥

**Pull request merged**
